### PR TITLE
Make completions work for commands invoked with xcrun

### PR DESCRIPTION
**Pull request by odnoletkov**
- Use built-in function to complete command in xcrun
- Add another directory to find xcrun commands
- Make completions work for commands invoked with xcrun
- Remove shims

### CODE REVIEW

**Comment by keith** [comment]
sorry, i jumped the gun, was this one ready 🙃

**Comment by odnoletkov** [comment]
lol, from my side looked like I pushed directly to your master accidentally.. took me some time to realize

Yeah this is good to merge, not all Xcode 14 updates are covered though. I'll submit a PR for two new subcommands (legacy, runtime) a bit later, thanks

**Comment by keith** [comment]
sounds great, thanks! do you want me to release now?

**Comment by keith** [comment]
eh i invited you to the repo too

**Comment by odnoletkov** [comment]
no, let's release after these two new subcommands are added too

**Comment by keith** [comment]
sg

**Pull request merged**
